import 'package:path/path.dart' as path;

/// HTTP helpers for guest web-share downloads.
class WebShareHttpUtil {
  WebShareHttpUtil._();

  static final RegExp _tokenPattern = RegExp(r'^[0-9a-f]{32}$');
  static final RegExp _fileIdPattern = RegExp(r'^[0-9a-f]+$');

  /// Share tokens are 128-bit hex strings.
  static bool isValidToken(String token) => _tokenPattern.hasMatch(token);

  /// File ids are hex strings generated by [WebShareService].
  static bool isValidFileId(String fileId) {
    if (fileId.isEmpty ||
        fileId.contains('/') ||
        fileId.contains('\\') ||
        fileId.contains('..')) {
      return false;
    }
    return _fileIdPattern.hasMatch(fileId);
  }

  /// Build a RFC 6266 Content-Disposition value safe for Dart HTTP headers.
  ///
  /// Header values must be Latin-1/ASCII. Non-ASCII names go only in the
  /// RFC 5987 `filename*` parameter; `filename` is an ASCII fallback.
  static String buildContentDisposition(String fileName) {
    final asciiName = asciiFallbackFileName(fileName);
    final encoded = Uri.encodeComponent(fileName).replaceAll('+', '%20');
    return "attachment; filename=\"$asciiName\"; filename*=UTF-8''$encoded";
  }

  /// ASCII-only fallback for the `filename=` parameter.
  static String asciiFallbackFileName(String fileName) {
    final base = path.basename(fileName);
    final buffer = StringBuffer();
    for (final unit in base.codeUnits) {
      final isAllowed = (unit >= 0x30 && unit <= 0x39) || // 0-9
          (unit >= 0x41 && unit <= 0x5A) || // A-Z
          (unit >= 0x61 && unit <= 0x7A) || // a-z
          unit == 0x2E || // .
          unit == 0x2D || // -
          unit == 0x5F; // _
      buffer.writeCharCode(isAllowed ? unit : 0x5F);
    }

    var result = buffer.toString().replaceAll(RegExp(r'_+'), '_');
    result = result.replaceAll(RegExp(r'^_+|_+$'), '');
    // Pure non-ASCII names collapse to ".pdf" / empty — normalize those too.
    if (result.isEmpty ||
        result == '.' ||
        result == '..' ||
        result.startsWith('.')) {
      final ext = path.extension(base);
      result = ext.isNotEmpty ? 'download$ext' : 'download';
    }
    if (result.length > 80) {
      final ext = path.extension(result);
      final stem = path.withoutExtension(result);
      final maxStem = 80 - ext.length;
      result = '${stem.substring(0, maxStem.clamp(1, stem.length))}$ext';
    }
    return result.replaceAll('"', '_');
  }
}
